Golangci lint v1.43.0 changes
storj/common pull request #13
Opened 2021-12-07 23:41 UTC by ethanadams

What: 
Changes to fix or ignore errors returned by golangci-lint v1.43.0
- dupArg: suspicious method call with the same argument and receiver (gocritic)
- File is not `gofmt`-ed with `-s` (gofmt)

Why:
- We want to upgrade golangci-lint
- 
Please describe the tests:
 - Test 1:
 - Test 2:
 
Please describe the performance impact:

## Code Review Checklist (to be filled out by reviewer)
 - [ ] NEW: Are there any Satellite database migrations? Are they forwards _and_ backwards compatible? 
 - [ ] Does the PR describe what changes are being made?
 - [ ] Does the PR describe why the changes are being made?
 - [ ] Does the code follow [our style guide](https://github.com/storj/docs/blob/main/code/Style.md)?
 - [ ] Does the code follow [our testing guide](https://github.com/storj/docs/blob/main/code/Testing.md)?
 - [ ] Is the PR appropriately sized? (If it could be broken into smaller PRs it should be)
 - [ ] Does the new code have enough tests? (*every* PR should have tests or justification otherwise. Bug-fix PRs especially)
 - [ ] Does the new code have enough documentation that answers "how do I use it?" and "what does it do?"? (both source documentation and [higher level](https://github.com/storj/docs), diagrams?)
 - [ ] Does any documentation need updating?
 - [ ] Do the database access patterns make sense?

2021-12-08 10:19 UTC, egonelbre requested changes

2021-12-08 10:19 UTC, egonelbre commented on fpath/path_unix_test.go
> -// +build linux darwin
This old version must stay in place for old Go versions.

2021-12-08 10:19 UTC, egonelbre commented on storj/node_test.go
> +		require.Equal(t, 0, b.Compare(b)) //nolint: gocritic
Is there a way to specific a specific reason instead of disabling the whole linter?

2021-12-08 10:23 UTC, egonelbre commented
Also based on the comments, you shouldn't need to update them manually. You can use `go fmt ./...` to fix them automatically.

2021-12-09 15:29 UTC, egonelbre approved these changes

2021-12-09 15:29 UTC, stefanbenten approved these changes

2021-12-10 12:56 UTC, egonelbre commented
run jenkins

2021-12-10 13:25 UTC, egonelbre commented
run jenkins

2021-12-10 13:37 UTC, merged